/**
 * Centralized sandbox enforcement — auto-generated by harness-emit-code
 */
export function assertSandbox(mode: string, operation: string): void {
  if (mode === "read_only") {
    return;
  }
  throw new Error(`Sandbox violation: write mode not allowed for ${operation}`);
}
