#!/usr/bin/env bun
// tsc-no-emit.test.mjs
// Tier-2: read a small TS fixture that exercises the sandbox pattern,
// run tsc --noEmit on it, assert exit code 0.
//
// ALL cases MUST FAIL because the emit-code stage hasn't run yet (pre-T10).
// The fixture path represents what the emit-code stage would generate.
// After T10, all MUST PASS.
//
// Run with: bun test tests/tsc-no-emit.test.mjs

import { test, expect } from "bun:test";
import { writeFileSync, mkdtempSync, rmSync, existsSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { execSync } from "child_process";

const KIT = join(import.meta.dir, "..");
// The path where emit-code would write generated tool files
const EMIT_OUTPUT_DIR = join(KIT, "harness-emit-code", "output");
const EMIT_SKILL_PATH = join(KIT, "harness-emit-code", "SKILL.md");

// THIS TEST MUST FAIL until emit-code stage exists
function assertEmitCodeStageExists() {
  expect(existsSync(EMIT_SKILL_PATH)).toBe(true);
}

// Inline TS fixture that exercises the sandbox pattern:
// - inline assertSandbox helper (matching the emit-code adapter template)
// - exports a function with sandbox guard
// - satisfies strict TypeScript
const SANDBOX_FIXTURE = [
  "/**",
  " * REST GET wrapper — auto-generated by harness-emit-code",
  " */",
  "",
  "// --- Sandbox enforcement ---",
  "",
  'const ALLOWED_PATHS: string[] = ["src", "tests", "tools"];',
  "",
  "function assertSandbox(mode: string, operation: string): void {",
  '  if (mode === "read_only") {',
  "    return;",
  "  }",
  '  throw new Error(`Sandbox violation: write mode not allowed for ${operation}`);',
  "}",
  "",
  "export function restGet(input: unknown): unknown {",
  '  assertSandbox("read_only", "restGet");',
  "  // TODO: implement REST GET wrapper",
  "  return input;",
  "}",
  "",
  'export const VERSION = "0.3.0";',
].join("\n");

test("emit_code_output_directory_exists", () => {
  // THIS TEST MUST FAIL until emit-code stage creates its output directory
  expect(existsSync(EMIT_OUTPUT_DIR)).toBe(true);
});

test("tsc_no_emit_on_sandbox_fixture_passes", () => {
  // THIS TEST MUST FAIL until emit-code stage exists
  assertEmitCodeStageExists();

  // Save fixture and run tsc
  const tmp = mkdtempSync(join(tmpdir(), "tsc-noemit-"));
  try {
    const fixturePath = join(tmp, "sandbox-tool.ts");
    const tsconfigPath = join(tmp, "tsconfig.json");
    writeFileSync(fixturePath, SANDBOX_FIXTURE);
    writeFileSync(tsconfigPath, JSON.stringify({
      compilerOptions: {
        strict: true,
        noEmit: true,
        target: "ESNext",
        module: "nodenext",
        moduleResolution: "nodenext",
        skipLibCheck: true,
      },
      include: ["sandbox-tool.ts"],
    }, null, 2));

    const result = execSync("tsc --noEmit --project " + tsconfigPath, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    expect(result).toBeDefined();
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
});
